# Generated by Django 5.2.7 on 2025-12-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description_snippet', models.TextField(help_text='Snippet of JD for reference')),
                ('resume_filename', models.CharField(max_length=255)),
                ('final_score', models.FloatField()),
                ('keyword_score', models.FloatField()),
                ('semantic_score', models.FloatField()),
                ('formatting_score', models.FloatField()),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
