# Generated by Django 5.2.7 on 2025-12-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysisresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='full_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
