# Generated by Django 6.0 on 2026-05-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_analysisresult_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='job_description_full',
            field=models.TextField(blank=True, default='', help_text='Full JD text for AI features'),
        ),
    ]
